#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Android_ePUB_reader_for_Xamarin.Resource", IsApplication=true)]

namespace Android_ePUB_reader_for_Xamarin
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int bookmark_dialog_goto_button = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int bookmark_dialog_set_button = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int bookmark_dialog_start_speech = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int bookmark_dialog_stop_speech = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int epub_title = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int menu_bookmark = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int menu_chapters = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int menu_pick_epub = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int webview = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int epub_list_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int options_menu = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_main = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f04000f
			public const int bookmark_dialog_goto_button = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int bookmark_dialog_set_button = 2130968590;
			
			// aapt resource value: 0x7f040010
			public const int bookmark_dialog_start_speech = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int bookmark_dialog_stop_speech = 2130968593;
			
			// aapt resource value: 0x7f04000d
			public const int bookmark_dialog_title = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int end_of_book = 2130968588;
			
			// aapt resource value: 0x7f040008
			public const int epub_title = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int menu_bookmark = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int menu_chapters = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int menu_pick_epub = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int menu_settings = 2130968578;
			
			// aapt resource value: 0x7f040009
			public const int no_book_selected = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int no_epub_found = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int not_implemented = 2130968586;
			
			// aapt resource value: 0x7f040012
			public const int options_menu_title = 2130968594;
			
			// aapt resource value: 0x7f040007
			public const int sd_card_not_mounted = 2130968583;
			
			// aapt resource value: 0x7f04000b
			public const int something_is_badly_broken = 2130968587;
			
			// aapt resource value: 0x7f040014
			public const int table_of_contents_missing = 2130968596;
			
			// aapt resource value: 0x7f040013
			public const int text_to_speech_not_installed = 2130968595;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
